# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "aioesphomeapi" = super.buildPythonPackage rec {
    pname = "aioesphomeapi";
    version = "35.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a4/e3/22f7e8ce628d0a01d158ba22bf5658c8bf584a1b36e145da7240defa1b72/aioesphomeapi-35.0.1.tar.gz";
      sha256 = "1m9fcd1dmlq6h9sg3ans8fa7p89s9qm8gwizyyzr7npqlswn27xg";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."aiohappyeyeballs"
      self."async-interrupt"
      self."async-timeout"
      self."chacha20poly1305-reuseable"
      self."cryptography"
      self."noiseprotocol"
      self."protobuf"
      self."zeroconf"
    ];
  };
  "aiohappyeyeballs" = super.buildPythonPackage rec {
    pname = "aiohappyeyeballs";
    version = "2.6.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0f/15/5bf3b99495fb160b63f95972b81750f18f7f4e02ad051373b669d17d44f2/aiohappyeyeballs-2.6.1-py3-none-any.whl";
      sha256 = "1f0z6c4iydxh09w5ka82556j11g4jzlq8bawkk4jbjvm9f7vljgk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "aiohttp" = super.buildPythonPackage rec {
    pname = "aiohttp";
    version = "3.13.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1c/ce/3b83ebba6b3207a7135e5fcaba49706f8a4b6008153b4e30540c982fae26/aiohttp-3.13.2.tar.gz";
      sha256 = "1jns53r902wwmyr8mzl8pspy61nd63fjrb9wxgvgxbl6q596l5s0";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."aiohappyeyeballs"
      self."aiosignal"
      self."async-timeout"
      self."attrs"
      self."frozenlist"
      self."multidict"
      self."propcache"
      self."yarl"
    ];
  };
  "aiosignal" = super.buildPythonPackage rec {
    pname = "aiosignal";
    version = "1.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fb/76/641ae371508676492379f16e2fa48f4e2c11741bd63c48be4b12a6b09cba/aiosignal-1.4.0-py3-none-any.whl";
      sha256 = "0bp81wd9xc9z1xxmkq5v1q5wzw4zhc596qwyji8hb69bp7w46ch5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."frozenlist"
      self."typing-extensions"
    ];
  };
  "amqp" = super.buildPythonPackage rec {
    pname = "amqp";
    version = "5.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/26/99/fc813cd978842c26c82534010ea849eee9ab3a13ea2b74e95cb9c99e747b/amqp-5.3.1-py3-none-any.whl";
      sha256 = "18l0g08mzab1hswpkm1jsvrl07mgnirdd4rshd8i4zaf3fg33cs3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."vine"
    ];
  };
  "astral" = super.buildPythonPackage rec {
    pname = "astral";
    version = "3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2d/80/d6edd9c3259913cfe39aff2bea4da65de5ad0235a578405e37aabace5f2c/astral-3.2-py3-none-any.whl";
      sha256 = "10szhpzzi302fbk11nwqqls628m3s9v144xycvk4minly2iljyyb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "async-interrupt" = super.buildPythonPackage rec {
    pname = "async-interrupt";
    version = "1.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5a/77/060b972fa7819fa9eea9a70acf8c7c0c58341a1e300ee5ccb063e757a4a7/async_interrupt-1.2.2-py3-none-any.whl";
      sha256 = "0b7c7r8qk546hfn0srvfrg9bn6rqlkl3lsca31azxdfg9a4fp38a";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "async-timeout" = super.buildPythonPackage rec {
    pname = "async-timeout";
    version = "5.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fe/ba/e2081de779ca30d473f21f5b30e0e737c438205440784c7dfc81efc2b029/async_timeout-5.0.1-py3-none-any.whl";
      sha256 = "0v77gzkjk90zg9d41jfap9j86v09bssrh8zcax2kb1gzcsaq1qrr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "asyncio-mqtt" = super.buildPythonPackage rec {
    pname = "asyncio-mqtt";
    version = "0.16.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2a/64/c8a8c2ed51f3c1f4b8d2f244424d3bad3fbd4333eb01589c6b00a6dd2c04/asyncio_mqtt-0.16.2-py3-none-any.whl";
      sha256 = "0wddm1ca8aymq2kzlgblhf877p9c4qc94ggzlxwqf94bchnflw7y";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."paho-mqtt"
      self."typing-extensions"
    ];
  };
  "attrs" = super.buildPythonPackage rec {
    pname = "attrs";
    version = "25.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3a/2a/7cc015f5b9f5db42b7d48157e23356022889fc354a2813c15934b7cb5c0e/attrs-25.4.0-py3-none-any.whl";
      sha256 = "0wrkgaslfj6iy65vlsp2rj6mpqddv2v5p0wpip26mcxk3wm7xkxd";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "bcoding" = super.buildPythonPackage rec {
    pname = "bcoding";
    version = "1.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9d/2f/6ee83fc7ec45bff8b1cf54f45acb61b00dd6ffacd68639e35fc247ae9f21/bcoding-1.5-py2.py3-none-any.whl";
      sha256 = "02y11vf55zq555m9p8qpa0a9jvwjsb0prywxd1m07kxi4v2mwm5k";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "billiard" = super.buildPythonPackage rec {
    pname = "billiard";
    version = "4.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a6/80/ef8dff49aae0e4430f81842f7403e14e0ca59db7bbaf7af41245b67c6b25/billiard-4.2.2-py3-none-any.whl";
      sha256 = "0mwlh92r2fj7h2sv0xblxp3z6ck25an3lwkhykgavihw1p7mvh2b";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "boltons" = super.buildPythonPackage rec {
    pname = "boltons";
    version = "25.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/45/7f/0e961cf3908bc4c1c3e027de2794f867c6c89fb4916fc7dba295a0e80a2d/boltons-25.0.0-py3-none-any.whl";
      sha256 = "0qnalsim9qj3j3m3i2cklgn6da1fnq04vdfijxa731c9ya5v77yw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "casttube" = super.buildPythonPackage rec {
    pname = "casttube";
    version = "0.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0a/d2/0f5006892e07ea342d57dbeda46027e99a097ffb6218bee1e37f9776ed95/casttube-0.2.1-py3-none-any.whl";
      sha256 = "1cimr0k1hln0f4wjmzv96lk3mda02qyf03gkkjax7slygw01iw9n";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."requests"
    ];
  };
  "celery" = super.buildPythonPackage rec {
    pname = "celery";
    version = "5.5.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c9/af/0dcccc7fdcdf170f9a1585e5e96b6fb0ba1749ef6be8c89a6202284759bd/celery-5.5.3-py3-none-any.whl";
      sha256 = "09fmcmyklhg83jjdzj84i5b5kf8n4i4clr24d6afxb2pf2h62mqb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."billiard"
      self."click"
      self."click-didyoumean"
      self."click-plugins"
      self."click-repl"
      self."kombu"
      self."python-dateutil"
      self."vine"
    ];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2025.11.12";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/70/7d/9bc192684cea499815ff478dfcdc13835ddf401365057044fb721ec6bddb/certifi-2025.11.12-py3-none-any.whl";
      sha256 = "0jrd0qnryi4mryf91nx6vgw0x0ppq8ppiv5pjqnmrg8b0f88gplp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cffi" = super.buildPythonPackage rec {
    pname = "cffi";
    version = "2.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/eb/56/b1ba7935a17738ae8453301356628e8147c79dbb825bcbc73dc7401f9846/cffi-2.0.0.tar.gz";
      sha256 = "0aambnn8q1jcyshfs002lapi90nypn6h9bh1c3iry4r1j28bbla4";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pycparser"
    ];
  };
  "chacha20poly1305-reuseable" = super.buildPythonPackage rec {
    pname = "chacha20poly1305-reuseable";
    version = "0.13.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fa/30/a4e44159996e832512f93ec6db89756ed72fe454ce3de1978e3a39c10bcd/chacha20poly1305_reuseable-0.13.2-py3-none-any.whl";
      sha256 = "0j0h132fkiz1gfi3cm3cigcavyivmbylp7pgrwdsb7sac31sgny7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cryptography"
    ];
  };
  "charset-normalizer" = super.buildPythonPackage rec {
    pname = "charset-normalizer";
    version = "3.4.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/13/69/33ddede1939fdd074bce5434295f38fae7136463422fe4fd3e0e89b98062/charset_normalizer-3.4.4.tar.gz";
      sha256 = "06p20hsbfmg9pdc307ffnb7nwfmlwyw06dp4423z4d8w262pjlwl";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "click" = super.buildPythonPackage rec {
    pname = "click";
    version = "8.1.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/d4/7ebdbd03970677812aac39c869717059dbb71a4cfc033ca6e5221787892c/click-8.1.8-py3-none-any.whl";
      sha256 = "1ck3f812hql67a8bfafkq30xjqmvjzsd38hjcyh7h5fhpsxk5hb3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "click-didyoumean" = super.buildPythonPackage rec {
    pname = "click-didyoumean";
    version = "0.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1b/5b/974430b5ffdb7a4f1941d13d83c64a0395114503cc357c6b9ae4ce5047ed/click_didyoumean-0.3.1-py3-none-any.whl";
      sha256 = "0z0iqgki0764zb866zlmk3ml2am205kzp8l3cpyz59gygh0bcjsw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."click"
    ];
  };
  "click-plugins" = super.buildPythonPackage rec {
    pname = "click-plugins";
    version = "1.1.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3d/9a/2abecb28ae875e39c8cad711eb1186d8d14eab564705325e77e4e6ab9ae5/click_plugins-1.1.1.2-py2.py3-none-any.whl";
      sha256 = "19kaxc7iprykgf0vlicp9nqal8rcin7fgw3v87sw3zrk71s6b380";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."click"
    ];
  };
  "click-repl" = super.buildPythonPackage rec {
    pname = "click-repl";
    version = "0.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/40/9d857001228658f0d59e97ebd4c346fe73e138c6de1bce61dc568a57c7f8/click_repl-0.3.0-py3-none-any.whl";
      sha256 = "04mqa7myxzm75lw9js2c14f7a5n3galrsfm3h1hyi3fsp3g0czpv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."click"
      self."prompt-toolkit"
    ];
  };
  "cryptography" = super.buildPythonPackage rec {
    pname = "cryptography";
    version = "46.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9f/33/c00162f49c0e2fe8064a62cb92b93e50c74a72bc370ab92f86112b33ff62/cryptography-46.0.3.tar.gz";
      sha256 = "18glhn902jsammcdkha55r65pqww9lln5cs5wwn05vag20w79cd8";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cffi"
      self."typing-extensions"
    ];
  };
  "frozenlist" = super.buildPythonPackage rec {
    pname = "frozenlist";
    version = "1.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2d/f5/c831fac6cc817d26fd54c7eaccd04ef7e0288806943f7cc5bbf69f3ac1f0/frozenlist-1.8.0.tar.gz";
      sha256 = "1b9ikbaj0c5z96fkyq1q3xpsa08hlkbq2w7w936zchnqv2g85piy";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "3.11";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0e/61/66938bbb5fc52dbdf84594873d5b51fb1f7c7794e9c0f5bd885f30bc507b/idna-3.11-py3-none-any.whl";
      sha256 = "1sipr9kdjcmwjm3lc6dx83qk6j4dq7lnyvhy15jazvwxkps8f6kp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "ifaddr" = super.buildPythonPackage rec {
    pname = "ifaddr";
    version = "0.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9c/1f/19ebc343cc71a7ffa78f17018535adc5cbdd87afb31d7c34874680148b32/ifaddr-0.2.0-py3-none-any.whl";
      sha256 = "0j57p1vp287f3sxi2sddmxs2dmgm61005qkj5nqnmwg6rw2h6ph8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "kombu" = super.buildPythonPackage rec {
    pname = "kombu";
    version = "5.5.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ef/70/a07dcf4f62598c8ad579df241af55ced65bed76e42e45d3c368a6d82dbc1/kombu-5.5.4-py3-none-any.whl";
      sha256 = "1f7y2m8h3hl5rpdg4nihbrn53labz3yx3w8qwpc9g213giax0bm1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."amqp"
      self."packaging"
      self."tzdata"
      self."vine"
    ];
  };
  "multidict" = super.buildPythonPackage rec {
    pname = "multidict";
    version = "6.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/80/1e/5492c365f222f907de1039b91f922b93fa4f764c713ee858d235495d8f50/multidict-6.7.0.tar.gz";
      sha256 = "1xg6x42z7slzw2976ryqk4j2p9n0m77ika7yimbjwa6acnd9vsf6";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "noiseprotocol" = super.buildPythonPackage rec {
    pname = "noiseprotocol";
    version = "0.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9d/e1/76e4694201d67b93a6f1644b2588b4a3d965419fe189416e3496cf415db5/noiseprotocol-0.3.1-py3-none-any.whl";
      sha256 = "049inamv4s75vgkipd18i8v7vqnf2a5kx2zx1z7kd5j370x606if";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cryptography"
    ];
  };
  "packaging" = super.buildPythonPackage rec {
    pname = "packaging";
    version = "25.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/20/12/38679034af332785aac8774540895e234f4d07f7545804097de4b666afd8/packaging-25.0-py3-none-any.whl";
      sha256 = "1154669ydc149dash6yaf3n2byqiqvajf8isdc282xgin7r2wmr9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "paho-mqtt" = super.buildPythonPackage rec {
    pname = "paho-mqtt";
    version = "2.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c4/cb/00451c3cf31790287768bb12c6bec834f5d292eaf3022afc88e14b8afc94/paho_mqtt-2.1.0-py3-none-any.whl";
      sha256 = "1vpy124da6y5s9aj9ps08m2dfbvfw33ih9w1wfvccnzd6jdvmfbd";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "prompt-toolkit" = super.buildPythonPackage rec {
    pname = "prompt-toolkit";
    version = "3.0.52";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/03/0d3ce49e2505ae70cf43bc5bb3033955d2fc9f932163e84dc0779cc47f48/prompt_toolkit-3.0.52-py3-none-any.whl";
      sha256 = "0mcrl7bgr58hqavkkp32ly8ln16civbdhnny8x1jhcxx7fd67b4s";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."wcwidth"
    ];
  };
  "propcache" = super.buildPythonPackage rec {
    pname = "propcache";
    version = "0.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/da/e9fc233cf63743258bff22b3dfa7ea5baef7b5bc324af47a0ad89b8ffc6f/propcache-0.4.1.tar.gz";
      sha256 = "0gbwr4il9v049wvspi3wal73f85ykbsfqdszami07s1pqsl0g0gl";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "protobuf" = super.buildPythonPackage rec {
    pname = "protobuf";
    version = "6.33.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/19/ff/64a6c8f420818bb873713988ca5492cba3a7946be57e027ac63495157d97/protobuf-6.33.0.tar.gz";
      sha256 = "0m69i52qkf42icvhqa5y071ivfr07fwwgy28qlq7f0yjr3ah60ql";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pychromecast" = super.buildPythonPackage rec {
    pname = "pychromecast";
    version = "13.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/98/bd/3aebe1ffce785940e48252c70942bf7c384d9b7e9c7d982ce18f193efae5/PyChromecast-13.1.0-py2.py3-none-any.whl";
      sha256 = "0qsn65sp0ix95qll1krj3amlwh6jiwgil464bbyx9cny83bwdhya";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."casttube"
      self."protobuf"
      self."zeroconf"
    ];
  };
  "pycparser" = super.buildPythonPackage rec {
    pname = "pycparser";
    version = "2.23";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/e3/59cd50310fc9b59512193629e1984c1f95e5c8ae6e5d8c69532ccc65a7fe/pycparser-2.23-py3-none-any.whl";
      sha256 = "0d2r3bw5mbqdan521f1xxqmsz7qakrr07b09mff4flxdzg9yiip5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python-dateutil" = super.buildPythonPackage rec {
    pname = "python-dateutil";
    version = "2.9.0.post0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/57/56b9bcc3c9c6a792fcbaf139543cee77261f3651ca9da0c93f5c1221264b/python_dateutil-2.9.0.post0-py2.py3-none-any.whl";
      sha256 = "09q48zvsbagfa3w87zkd2c5xl54wmb9rf2hlr20j4a5fzxxvrcm8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "pytz" = super.buildPythonPackage rec {
    pname = "pytz";
    version = "2025.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/81/c4/34e93fe5f5429d7570ec1fa436f1986fb1f00c3e0f43a589fe2bbcd22c3f/pytz-2025.2-py2.py3-none-any.whl";
      sha256 = "001gxkq46b96nzhdwymxzgvcng4g90snyjwgxck4ri6qdllpdpsx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "radiale" = super.buildPythonPackage rec {
    pname = "radiale";
    version = "0.5.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/21/8a/ee5c50a89e5b4faaaed4f6c6d0d75eadcdf057b54ffe801f162e8b720eb3/radiale-0.5.2-py3-none-any.whl";
      sha256 = "0knf5h8hh83yn1wjrcpkwf8czidvjnhhzqc26dm93rzza9faw5f7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."aioesphomeapi"
      self."aiohttp"
      self."astral"
      self."asyncio-mqtt"
      self."bcoding"
      self."boltons"
      self."celery"
      self."pychromecast"
      self."pytz"
      self."websockets"
      self."zeroconf"
    ];
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.32.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1e/db/4254e3eabe8020b458f1a747140d32277ec7a271daf1d235b70dc0b4e6e3/requests-2.32.5-py3-none-any.whl";
      sha256 = "1dpz38b6lnn8fcad7kfiagagbc3djy3f35a24qrdakx36x3gjqi4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."charset-normalizer"
      self."idna"
      self."urllib3"
    ];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.17.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b7/ce/149a00dd41f10bc29e5921b496af8b574d8413afcd5e30dfa0ed46c2cc5e/six-1.17.0-py2.py3-none-any.whl";
      sha256 = "0x1jdic712dylbnyiqdj4xyxrlx0gaacynmbmkfiym4hxn8z68a7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "4.15.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/18/67/36e9267722cc04a6b9f15c7f3441c2363321a3ea07da7ae0c0707beb2a9c/typing_extensions-4.15.0-py3-none-any.whl";
      sha256 = "0j75qhcc0p627f464gd7kjcirdzcga5zl32a0w4ann2phk31kyph";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tzdata" = super.buildPythonPackage rec {
    pname = "tzdata";
    version = "2025.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5c/23/c7abc0ca0a1526a0774eca151daeb8de62ec457e77262b66b359c3c7679e/tzdata-2025.2-py2.py3-none-any.whl";
      sha256 = "1a37yr3j3kcs5lj95ssbv0aj44zsd0c70k84m0f25y8zl2nkyh0s";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "2.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a7/c2/fe1e52489ae3122415c51f387e221dd0773709bad6c6cdaa599e8a2c5185/urllib3-2.5.0-py3-none-any.whl";
      sha256 = "1p7hrw2cc75zyqbb49diqi371gxkis07225mfkii6spsq1ridc76";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "vine" = super.buildPythonPackage rec {
    pname = "vine";
    version = "5.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/03/ff/7c0c86c43b3cbb927e0ccc0255cb4057ceba4799cd44ae95174ce8e8b5b2/vine-5.1.0-py3-none-any.whl";
      sha256 = "1p5i3y0i6x5x52km00419iwy926sdzdf56lylhw1rzicig2g7za0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "wcwidth" = super.buildPythonPackage rec {
    pname = "wcwidth";
    version = "0.2.14";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/af/b5/123f13c975e9f27ab9c0770f514345bd406d0e8d3b7a0723af9d43f710af/wcwidth-0.2.14-py2.py3-none-any.whl";
      sha256 = "1qc294myh1nrvy302wkz5lpn086xbs09b62zgsazjc7fi865dfx7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "websockets" = super.buildPythonPackage rec {
    pname = "websockets";
    version = "15.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/21/e6/26d09fab466b7ca9c7737474c52be4f76a40301b08362eb2dbc19dcc16c1/websockets-15.0.1.tar.gz";
      sha256 = "1vldhbg4cww2mc6cdw27mc9xls1d87k5w1ff72hgpfkn43h4sm42";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "yarl" = super.buildPythonPackage rec {
    pname = "yarl";
    version = "1.22.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/57/63/0c6ebca57330cd313f6102b16dd57ffaf3ec4c83403dcb45dbd15c6f3ea1/yarl-1.22.0.tar.gz";
      sha256 = "0wdg8mkls6yhd8hzxlbqm9vwhxhkdy837zyrifx02i3xaxbqbgxy";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."idna"
      self."multidict"
      self."propcache"
    ];
  };
  "zeroconf" = super.buildPythonPackage rec {
    pname = "zeroconf";
    version = "0.148.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/67/46/10db987799629d01930176ae523f70879b63577060d63e05ebf9214aba4b/zeroconf-0.148.0.tar.gz";
      sha256 = "00hpd1phacfz99yinq9p6qqmyq1g7ml2s4a5v4ijwrgk7l9cmz03";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ifaddr"
    ];
  };
}
